"use client";

import * as React from "react";
import Link from "next/link";
import { toast } from "sonner";
import { DownloadIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { memberOf } from "@/components/custom/bits";
import { API_URL, getReports, getWorkspaces } from "@/lib/api";
import { fmtTime } from "@/lib/format";
import { ME } from "@/lib/mock-data";

interface ReportRow {
  id: string;
  name: string;
  kind: "PDF";
  at: number;
  by: string;
  traceId: number;
  workspaceId?: string;
}

export default function ReportsPage() {
  const [rows, setRows] = React.useState<ReportRow[]>([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    let cancelled = false;

    async function loadReports() {
      try {
        setLoading(true);

        const [reports, workspaces] = await Promise.all([
          getReports(500),
          getWorkspaces(100),
        ]);

        const workspaceByTrace = new Map(
          workspaces
            .filter((workspace) => workspace.traceId != null)
            .map((workspace) => [workspace.traceId, workspace]),
        );

        const nextRows: ReportRow[] = reports.map((report) => {
          const workspace = workspaceByTrace.get(report.trace_id);

          return {
            id: `r-${report.trace_id}`,
            name: `Investigation report – trace ${report.trace_id}.pdf`,
            kind: "PDF",
            at: report.created_at,
            by: ME,
            traceId: report.trace_id,
            workspaceId: workspace?.id,
          };
        });

        if (!cancelled) {
          setRows(nextRows.sort((a, b) => b.at - a.at));
        }
      } catch (error) {
        console.error("Failed to load reports:", error);

        if (!cancelled) {
          toast.error("Failed to load reports");
          setRows([]);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    loadReports();

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Reports & evidence</CardTitle>
        <CardDescription>
          Every generated report and hashed evidence bundle across all
          workspaces
        </CardDescription>
      </CardHeader>

      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>File</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Case</TableHead>
              <TableHead>Generated by</TableHead>
              <TableHead>When</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>

          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell
                  colSpan={6}
                  className="text-center text-muted-foreground"
                >
                  Loading reports…
                </TableCell>
              </TableRow>
            ) : rows.length === 0 ? (
              <TableRow>
                <TableCell
                  colSpan={6}
                  className="text-center text-muted-foreground"
                >
                  No reports found.
                </TableCell>
              </TableRow>
            ) : (
              rows.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="font-medium">{r.name}</TableCell>

                  <TableCell>
                    <Badge variant="outline">{r.kind}</Badge>
                  </TableCell>

                  <TableCell>
                    {r.workspaceId ? (
                      <Link
                        href={`/workspaces/${r.workspaceId}`}
                        className="hover:underline"
                      >
                        {r.workspaceId}
                      </Link>
                    ) : (
                      "—"
                    )}
                  </TableCell>

                  <TableCell>{memberOf(r.by).name}</TableCell>

                  <TableCell className="text-xs text-muted-foreground">
                    {fmtTime(r.at)}
                  </TableCell>

                  <TableCell className="text-right">
                    <a
                      href={`${API_URL}/report/${r.traceId}`}
                      target="_blank"
                      rel="noreferrer"
                    >
                      <Button
                        size="xs"
                        variant="outline"
                        nativeButton={false}
                        render={<span />}
                      >
                        <DownloadIcon />
                        Open
                      </Button>
                    </a>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
