"use client"

import Link from "next/link"
import { toast } from "sonner"
import { DownloadIcon } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { memberOf } from "@/components/custom/bits"
import { API_URL } from "@/lib/api"
import { fmtTime } from "@/lib/format"
import { useStore } from "@/lib/store"

export default function ReportsPage() {
  const { state } = useStore()
  const rows = state.workspaces.flatMap((w) => w.reports.map((r) => ({ ...r, ws: w }))).sort((a, b) => b.at - a.at)
  return (
    <Card>
      <CardHeader><CardTitle>Reports & evidence</CardTitle><CardDescription>Every generated report and hashed evidence bundle across all workspaces</CardDescription></CardHeader>
      <CardContent>
        <Table>
          <TableHeader><TableRow><TableHead>File</TableHead><TableHead>Type</TableHead><TableHead>Case</TableHead><TableHead>Generated by</TableHead><TableHead>When</TableHead><TableHead /></TableRow></TableHeader>
          <TableBody>
            {rows.map((r) => (
              <TableRow key={r.id}>
                <TableCell className="font-medium">{r.name}</TableCell>
                <TableCell><Badge variant="outline">{r.kind}</Badge></TableCell>
                <TableCell><Link href={`/workspaces/${r.ws.id}`} className="hover:underline">{r.ws.id}</Link></TableCell>
                <TableCell>{memberOf(r.by).name}</TableCell>
                <TableCell className="text-xs text-muted-foreground">{fmtTime(r.at)}</TableCell>
                <TableCell className="text-right">
                  {r.ws.traceId
                    ? <a href={`${API_URL}/${r.kind === "PDF" ? "report" : "evidence"}/${r.ws.traceId}`} target="_blank" rel="noreferrer"><Button size="xs" variant="outline" nativeButton={false} render={<span />}><DownloadIcon />Open</Button></a>
                    : <Button size="xs" variant="outline" onClick={() => toast.info("Demo case – run a live trace to open the real PDF")}><DownloadIcon />Open</Button>}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  )
}
