"use client";

import * as React from "react";
import Link from "next/link";
import { toast } from "sonner";
import { DownloadIcon, FileTextIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { memberOf } from "@/components/custom/bits";
import { API_URL, getReports, getWorkspaces } from "@/lib/api";
import { fmtTime } from "@/lib/format";
import { ME } from "@/lib/mock-data";

interface ReportRow {
  id: string;
  name: string;
  kind: "PDF";
  at: number;
  by: string;
  traceId: number;
  workspaceId?: string;
}

export default function ReportsPage() {
  const [rows, setRows] = React.useState<ReportRow[]>([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    let cancelled = false;

    async function loadReports() {
      try {
        setLoading(true);

        const [reports, workspaces] = await Promise.all([
          getReports(500),
          getWorkspaces(100),
        ]);

        const workspaceByTrace = new Map(
          workspaces
            .filter((workspace) => workspace.traceId != null)
            .map((workspace) => [workspace.traceId, workspace]),
        );

        const nextRows: ReportRow[] = reports.map((report) => {
          const workspace = workspaceByTrace.get(report.trace_id);

          return {
            id: `r-${report.trace_id}`,
            name: `Investigation report – trace ${report.trace_id}.pdf`,
            kind: "PDF",
            at: report.created_at,
            by: ME,
            traceId: report.trace_id,
            workspaceId: workspace?.id,
          };
        });

        if (!cancelled) {
          setRows(nextRows.sort((a, b) => b.at - a.at));
        }
      } catch (error) {
        console.error("Failed to load reports:", error);

        if (!cancelled) {
          toast.error("Failed to load reports");
          setRows([]);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    loadReports();

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <Card className="border-cyan-400/[0.14] bg-[linear-gradient(145deg,rgba(10,26,48,0.78),rgba(3,11,23,0.88))] shadow-[0_16px_40px_rgba(0,0,0,0.4)]">
      <CardHeader>
        <CardTitle className="flex items-center gap-2.5 text-2xl font-bold tracking-tight text-slate-100">
          <FileTextIcon className="size-5 text-cyan-400" />
          Reports & evidence
        </CardTitle>
        <CardDescription className="text-slate-400 text-xs">
          Every generated report and hashed evidence bundle across all
          workspaces
        </CardDescription>
      </CardHeader>

      <CardContent>
        <Table>
          <TableHeader className="border-cyan-400/[0.12]">
            <TableRow className="border-cyan-400/[0.08] hover:bg-transparent">
              <TableHead className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-400">File</TableHead>
              <TableHead className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-400">Type</TableHead>
              <TableHead className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-400">Case</TableHead>
              <TableHead className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-400">Generated by</TableHead>
              <TableHead className="text-[11px] font-semibold uppercase tracking-[0.1em] text-slate-400">When</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>

          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell
                  colSpan={6}
                  className="py-12 text-center text-slate-500 font-mono text-xs"
                >
                  Loading reports…
                </TableCell>
              </TableRow>
            ) : rows.length === 0 ? (
              <TableRow>
                <TableCell
                  colSpan={6}
                  className="py-12 text-center text-slate-500"
                >
                  No reports found.
                </TableCell>
              </TableRow>
            ) : (
              rows.map((r) => (
                <TableRow key={r.id} className="border-cyan-400/[0.08] hover:bg-cyan-500/[0.04] transition-colors">
                  <TableCell className="font-medium text-slate-200">{r.name}</TableCell>

                  <TableCell>
                    <Badge variant="outline" className="border-cyan-400/25 bg-cyan-500/10 text-cyan-300 font-mono text-xs">
                      {r.kind}
                    </Badge>
                  </TableCell>

                  <TableCell>
                    {r.workspaceId ? (
                      <Link
                        href={`/workspaces/${r.workspaceId}`}
                        className="font-mono text-xs font-semibold text-cyan-300 hover:text-cyan-200 hover:underline"
                      >
                        {r.workspaceId}
                      </Link>
                    ) : (
                      "—"
                    )}
                  </TableCell>

                  <TableCell className="text-xs text-slate-300">{memberOf(r.by).name}</TableCell>

                  <TableCell className="font-mono text-xs text-slate-500">
                    {fmtTime(r.at)}
                  </TableCell>

                  <TableCell className="text-right">
                    <a
                      href={`${API_URL}/report/${r.traceId}`}
                      target="_blank"
                      rel="noreferrer"
                    >
                      <Button
                        size="xs"
                        variant="outline"
                        nativeButton={false}
                        render={<span />}
                        className="border-cyan-400/25 bg-slate-900/60 text-cyan-300 hover:border-cyan-400/45 hover:bg-cyan-500/10 hover:text-cyan-200"
                      >
                        <DownloadIcon className="size-3.5" />
                        Open
                      </Button>
                    </a>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
